version: '3.7'

services:

  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  alfresco:
    image: alfresco/alfresco-content-repository-community:6.2.1-A8
    environment:
        JAVA_OPTS: "
            -Ddb.driver=org.postgresql.Driver
            -Ddb.username=alfresco
            -Ddb.password=alfresco
            -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
            -Dsolr.host=solr6
            -Dsolr.port=8983
            -Dsolr.secureComms=none
            -Dsolr.base.url=/solr
            -Dindex.subsystem.name=solr6
            -Dshare.host=127.0.0.1
            -Dshare.port=8080
            -Dalfresco.host=localhost
            -Dalfresco.port=8080
            -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
            -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
            -Ddeployment.method=DOCKER_COMPOSE
            -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
            -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
            -Djodconverter.url=http://transform-core-aio:8090/
            -Dimg.url=http://transform-core-aio:8090/
            -Dtika.url=http://transform-core-aio:8090/
            -Dtransform.misc.url=http://transform-core-aio:8090/
            -Dcsrf.filter.enabled=false
            -Xms1500m -Xmx1500m
            "
    depends_on:
      - postgres
      - elasticsearch

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.2.1
    environment:
        JAVA_OPTS: " -Xms256m -Xmx1536m"
    ports:
        - 8090:8090

  share:
    image: alfresco/alfresco-share:6.2.1
    environment:
        REPO_HOST: "alfresco"
        REPO_PORT: "8080"
        JAVA_OPTS: "
            -Xms500m
            -Xmx500m
            -Dalfresco.host=localhost
            -Dalfresco.port=8080
            -Dalfresco.context=alfresco
            -Dalfresco.protocol=http
            "
    depends_on:
      - alfresco

  postgres:
    image: postgres:11.4
    environment:
        - POSTGRES_PASSWORD=alfresco
        - POSTGRES_USER=alfresco
        - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
        - 5432:5432

  solr6:
    image: searchservices:develop
    environment:
        #Solr needs to know how to register itself with Alfresco
        SOLR_ALFRESCO_HOST: "alfresco"
        SOLR_ALFRESCO_PORT: 8080
        #Alfresco needs to know how to call solr
        SOLR_SOLR_HOST: "solr6"
        SOLR_SOLR_PORT: 8983
        #Create the default alfresco and archive cores
        SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
        #HTTP by default
        ALFRESCO_SECURE_COMMS: "none"
        SOLR_JAVA_MEM: "-Xms2g -Xmx2g"
        SOLR_OPTS: "
            -Delastic.host=elasticsearch
            -Delastic.port=9200
            -Delastic.protocol=http
        "
    ports:
        - 8083:8983 #Browser port
    depends_on:
      - alfresco
      - elasticsearch

  activemq:
    image: alfresco/alfresco-activemq:5.15.8
    ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

  proxy:
    image: alfresco/acs-community-ngnix:1.0.0
    depends_on:
        - alfresco
    ports:
        - 8080:8080
    links:
        - alfresco
        - share
